### ISSUE TITLE
Logic of this condition

### ISSUE THREAD

**Issue by vaishnavm217** [yeephycho/widerface-to-tfrecord#3]
I don't understand the logic of these lines. Why are you hardcoding these? Why should the minimum bbox be 25 and 30?
https://github.com/yeephycho/widerface-to-tfrecord/blob/ae945f4ce55f89320a3d849e6d57535f43840ca3/widerface_To_TFRecord.py#L55-L56

**Comment by yeephycho** [comment]
Just my own preference, if the face size is too small, then, I chose to ignore it, you can modify.
